feat: add input component
Selleo/design-system pull request #17
Opened 2023-01-20 10:47 UTC by ZajoncM

2023-02-02 17:40 UTC, Matgorn commented
Update:
- refactor: handle all states and sizes within one input component
- style: update styles after changes global styles in `main` branch
- style: update styles after changes in [Figma](https://www.figma.com/file/aAZNLti1x7RHcKO2aaVdyh/Selleo-Design-System?node-id=1473%3A3352&t=MC6atK6e1XNZEjLS-4)

@k1eu @michalgren

2023-02-03 19:12 UTC, k1eu approved these changes

2023-02-03 19:13 UTC, k1eu requested changes
When both icons are present the placeholder is behind the icons

2023-02-06 09:00 UTC, Matgorn commented
> When both icons are present the placeholder is behind the icons

Fixed 👍

2023-02-06 13:21 UTC, k1eu requested changes

2023-02-06 13:21 UTC, k1eu commented on packages/selleo-tailwind/tailwind.config.cjs
> +      48: "48px",
weird size, can we try to stick to the extisting spacing or try to adjust design for it?

2023-02-07 12:10 UTC, Matgorn commented
Update:
- refactor: use a different approach without using position absolute, just flexbox instead
- chore: remove the 48px spacing from Tailwind config and usage
@k1eu @michalgren 

Closes #40

2023-02-20 18:25 UTC, k1eu approved these changes

2023-02-27 15:00 UTC, merged