feat: add sidebar page with example from figma design system
Selleo/design-system pull request #9
Opened 2023-01-18 16:55 UTC by Matgorn

PR includes:
- feat: add `PageTemplate.astro` component to display components related to the placement on the page
- feat: add sidebar variants (light and dark theme) based on [figma](https://www.figma.com/file/aAZNLti1x7RHcKO2aaVdyh/Selleo-Design-System?node-id=1179%3A338&t=2Uhcfa8c1Jgjj4I2-4)

2023-01-24 11:04 UTC, k1eu commented
closes: #24

2023-01-31 15:59 UTC, Matgorn commented
Update:
- Rebase branch with `main`
- Encapsulate icons to separate components
- Pull out `SidebarItem.tsx` component from `Sidebar.tsx` and setup preview page with visual representation
- Fix: styles after rebase with `main` branch
- Fix: content wrapper element tailwind classes overwrites directly assigned classes by higher specificity

@k1eu @michalgren

2023-02-01 10:38 UTC, k1eu requested changes

2023-02-01 10:38 UTC, k1eu commented on packages/selleo-design-core/src/Sidebar/Sidebar.tsx
> +      <div class="p-3 overflow-y-auto bg-white dark:bg-black relative h-full shadow-[#231f28]/5 shadow-[4px_0_16px]">
can you check if we can use here the shadows from design system and add them as variables?

2023-02-01 10:38 UTC, k1eu commented on packages/selleo-design-core/src/Sidebar/SidebarItem.tsx
> +        <span class="ml-[12px]">{label}</span>
possible to round it to nearest variable?

2023-02-01 10:38 UTC, k1eu commented on packages/selleo-design-core/src/Sidebar/SidebarItem.tsx
> +        <span class="ml-[12px]">{label}</span>
just let @michalgren know u did it cause the sidebar design is just taken from another app so it might be little off when it comes to consistency

2023-02-01 10:38 UTC, k1eu commented on apps/docs/src/pages/041-sidebarItem.mdx
> +/>
Can we have SidebarItem listed on the same page as sidebar?

2023-02-03 09:01 UTC, k1eu approved these changes

2023-02-03 12:55 UTC, merged